### ISSUE TITLE
Bundled "Roboto" font doesn't match live, up-to-date version of Roboto

### ISSUE THREAD

**Issue by smiley** [Elundris/Air-for-Steam#12]
I've installed the font, but afterwards web apps using Roboto turned from this:
![gpm_ok](https://cloud.githubusercontent.com/assets/354181/7045691/f5e699e4-de08-11e4-8138-ccdc300291df.png)
To this:
![gpm_bad](https://cloud.githubusercontent.com/assets/354181/7045679/e2c41544-de08-11e4-89ff-881c699e2ddb.png)

They should be updated, but in any case, overriding Roboto globally is a bad idea. How about renaming the actual font name of the bundled fonts to something like "Roboto for Air"? That way you can use any fonts you want without messing with other applications. This is done in [`powerline/fonts`](https://github.com/powerline/fonts) to avoid overriding the original fonts with Powerline's patched versions.

**Comment by Elundris** [comment]
The Roboto font that I've been using with Air is the official Roboto font from pre-material design. I was very hesitant to update to the new font due to spacing differences, but I'll use this as my excuse to switch over to the new one (since it's probably better anyway).

In the meantime, you can manually uninstall the fonts that were bundled with Air and get the new version from here: http://www.google.com/fonts/specimen/Roboto
