### ISSUE TITLE
[Steam] "Requests?"

### ISSUE THREAD

**Issue by sebie** [Elundris/Air-for-Steam#20]
Transcript from a [post](http://steamcommunity.com/groups/airforsteam/discussions/1/618459405722890623/) in the Air for Steam group.

-----

> If possible can you add these to the new update? In my opinion, these features look better than before.

> Here they are:

> The Friends tab right next the currency:
![friends](http://i.gyazo.com/2a81e16290c3037c064cf414c32b6a14.jpg)

> The "You've played" and "Lasted Played" Under the play tab:
![played](http://i.gyazo.com/57345bd395a05f9c0362b5a7b19f0294.png)

> I would use this version, but it doesnt support the new update that added broadcasts. 

> Also, how do you change the font of the "Recent News" and "Friends" under games?

> Ex: 
![example](http://i.gyazo.com/3bacd64cd3b20bd6580f518645586b00.png)

> (This is an old release)

> Heres a [link](http://www.mediafire.com/download/ux3bu61bltlh8l7/Air_Dark_Custom.zip) to my Air if you need it.

*End of Transcript*

-----

In my opinion, we should re-add `enhacement` , tag it and close it. But if you like anything from what he says, we can keep it open and tag it `todo`. I do like the `played` thing otherneath it, looks nicer?

**Comment by Elundris** [comment]
The friends online thing is something I don't plan on adding by default but I may be able to offer it as an option.

As for the last played, it does indeed look better below with the rectangular button, but it looks quite odd with the smaller circular style buttons. That's really the only reason I moved it in the newer builds.

I will answer the fonts question on the community group since it is unrelated to the enhancements.

**Comment by sebie** [comment]
Cool, thanks. :smiley:
