### ISSUE TITLE
Steam Wallet amount is just kind of floating with nothing around

### ISSUE THREAD

**Issue by 1112e** [Elundris/Air-for-Steam#26]
![](http://i.imgur.com/2hlakls.png)

How would it look swapped position with the notification area? (closer to buttons)

**Comment by sebie** [comment]
In my personal opinion, I would keep it up there, maybe closer to the menu items in fact. 

Added `enhacement` as it really is just a styling suggestion, not a bug etc. 

Thanks for contributing!

**Comment by Elundris** [comment]
I had it swapped originally, but it was causing issues when people had no money in their wallet. For some reason Steam decided to simply remove the wallet element when that happened and then you ended up with a bug where the notification icon appeared under the window controls.

I was trying to avoid hard coding the right margin because of the possibility of larger wallet sizes (or different currencies taking up more/less space), which leaves me in the pickle that you see here.

I do think this is the lesser of the two evils though.
