### ISSUE TITLE
Multiple visual issues in Shift+Tab, at least on Linux.

### ISSUE THREAD

**Issue by Mocha-Bean** [Elundris/Air-for-Steam#50]
I describe the issues over this screenshot:

![air4steamshifttab](http://i.imgur.com/Dr3aKSZ.png)

You'll probably have to open the image in a new tab to precisely see how the top of the text is chipped off.

Also, the popup in the bottom right upon joining a game that usually says "Access the Steam community while playing" is truncated to "Access the Steam..."

Air For Steam version 2015-0616; stock configuration.

I might add that I am using Infinality font rendering. This seems very likely to be relevant. https://wiki.archlinux.org/index.php/Infinality

`OS: Arch Linux`
`Kernel: x86_64 Linux 4.0.5-1-ARCH`
`Packages: 1330`
`Shell: bash 4.3.39`
`Resolution: 1920x1080`
`DE: XFCE4`
`WM: KWin`
`WM Theme: Numix`
`GTK Theme: Numix [GTK2], Not Found [GTK3]`
`Icon Theme: Numix-Circle`
`Font: Roboto 10`
`CPU: Intel Core i7-3610QM CPU @ 3.3GHz`
`GPU: GeForce GTX 660M`
`RAM: 16005MB`

**Comment by sebie** [comment]
From the four listed issues, here is how I would answer them.

-----

1) Buttons being truncated at the top:
I would imagine that you could change the dimensions of the text field[s] or it might be a % of your screen resolution.

2) Friends menu:
Seems like a minor positioning enhacement to me!

3) Text chipped off:
To be honest, I can't and wouldn't notice that. 

4) Settings placement
I would maybe suggest putting it on the other side with, the "Web Browser" and "Music"? Otherwise it seems like 2).

-----

Hope it sheds some light on my opinions on the visual issues. It could be Linux though, hmm.

Thanks for submitting the issue and @Elundris will be on it.

**Comment by Elundris** [comment]
These are all due to text sizes being slightly larger on Linux. In the long run, I think the solution is to conditionally set all Linux font sizes smaller in the _fonts.styles file.

This is something that I plan to do (for both Linux and OSX), but it may take some time.

**Comment by sebie** [comment]
Ok, at least we have it here to refrence if others have the same problem.

**Comment by Elundris** [comment]
I am closing this due to the overlay overhaul in the works: cca702b055f5aca105a19d6d983538613945eb89

Please feel free to re-open or make a new issue if there are issues with the new one.
