### ISSUE TITLE
Ctrl+click/middle mouse button click opens empty window

### ISSUE THREAD

**Issue by asser-dk** [Elundris/Air-for-Steam#56]
With the default steam skin, when you go into i.e. the steam store or workshop and ctrl+click something (or middle mouse button click for that matter) it opens the page for the selected thing in a new window.

When I try to do so with the Air skin (both 2015-0405 and 2015-0616) the following happens:

A new empty window opens (you can see a 1 px border on the edges of your screen) which hides steam and shows your desktop background image instead (icons on the desktop are hidden). If you drag another window into it you get the "cascading" effect.

I couldn't take a screenshot of the bug because all screenshots would show the steam window (not the new window) instead of the blank window, cascade bug and border.

OS is Windows, 8.1 64 bit.

Best screenshot I could find, addressing this issue.

![Air for Steam error](http://i.stack.imgur.com/4RQDU.jpg)

**Comment by sebie** [comment]
Hi @asser-dk thanks for submiting this issue.

The image you linked to (actually) helped, thanks. But as you are on Windows, you could use the following method to take a screenshot of your current screen; using Print Screen.

-----

Method:

1. Open enough windows (links), so the issue is visible.
2. Locate on your keyboard `PRTSC` and press it teice alone. Followed by twice with the FN key
  ![PRTSC](http://forums.toshiba.com/t5/image/serverpage/image-id/338iB7FE5452F821476F/image-size/original?v=mpbl-1&px=-1)
3. Open up Paint and paste (CTRL+V) to paste the image from step 2.
4. File>Save As>./Desktop/air-for-steam-issue-56
5 Upload that image to imgur.com or any equivalent service
6. Provide the link and done!

Thanks and feel free to comment back if you are unsure.

**Comment by Elundris** [comment]
I'm pretty sure this is the same issue you are addressing: http://steamcommunity.com/groups/airforsteam/discussions/0/620712364041881340/

If so, long story short: this is (to my best knowledge) a Steam bug related to skins that I am unable to fix. My only suggestion at this point is to avoid trying to open those links in a new tab.

**Comment by Elundris** [comment]
I was actually able to track down the cause of this issue with the help of Dirt Diglett. Long story short, it should now be semi-fixed.

More info here: http://steamcommunity.com/groups/airforsteam/discussions/0/530646080841040846/
