### ISSUE TITLE
Steam library issues

### ISSUE THREAD

**Issue by BluTree** [Elundris/Air-for-Steam#69]
I have 2 problems. The first is that i can't see much the screenshots on the library and i would like to increase the contrast of screenshots.
![capture](https://cloud.githubusercontent.com/assets/11920536/8728840/c0dac7ca-2be7-11e5-9fc5-e68fbed1a413.PNG)
The second is that I would change the emplacement of the thing framed in black to the frame red
![steam](https://cloud.githubusercontent.com/assets/11920536/8729044/0b963578-2be9-11e5-94d9-acdce94bcfca.PNG)
Your work is incredible! Continue like that !

**Comment by sebie** [comment]
With the first problem, you will have to wait for @Elundris . However with the second one, what "thing"? Is it the Categories or the spacing or something else? Please ellaborate.

Thank you! :)

**Comment by Elundris** [comment]
In order to make the screenshots more visible, you will need to reduce the alpha of the overlay color. You can do this by opening this file in a text editor: \Steam\skins\Air-for-Steam\Resource\themes\_light.styles

* Search for this line: `Details.Background			"184 184 184 150"`
* Change the 4th number (currently 150) to something less in order make the screenshots more visible.
* Save and restart Steam.

Moving the links section to the right-hand side is not going to be possible with the way the details page is laid out, sorry!
