### ISSUE TITLE
Increase Text Contrast in Library

### ISSUE THREAD

**Issue by JamesCoyle** [Elundris/Air-for-Steam#89]
![image](https://cloud.githubusercontent.com/assets/10384436/10489196/8497b12a-728b-11e5-875b-fd28d6630f32.png)

It can be quite hard to see which games are installed or not on certain screens. It would be nice if there were greater difference in the text color.

**Comment by Elundris** [comment]
Since this is more of a hardware-specific issue, I'll point you in the direction of how to manually edit it yourself. You'll need to open the file \Air-for-Steam\Resource\themes\_dark.styles and change the value of "A2TextSecondary" to a lower number.

Stick to multiples of 5, and write it as "Air###". You can also manually enter any rgba value if you'd prefer.

Save and restart Steam to test your changes.
